name: Spell Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  spell-check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check spelling
        uses: check-spelling/check-spelling@0.0.16-alpha
        with:
          project: .
